name: SSE CI/CD

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install style checker clang-format"
        run: sudo apt install clang-format
      - name: "Run style check"
        run: clang-format -i src/*.cpp src/*.hpp
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name : "Install libraries required to run pytest on diffusion code"
        run : pip install numpy matplotlib
      - name : "Install pytest"
        run: pip install -U pytest
      - name : "Install coverage"
        run: pip install -U coverage
      - name: "Run pytest"
        run: python -m pytest
      - name: "Run coverage"
        run: coverage run -m pytest
      - name: "Adding report to .coverage location"
        uses: actions/upload-artifact@v2
        with:
          name: Coverage-Report
          path: .coverage
          retention-days: 1
  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name : "Install coverage"
        run: pip install -U coverage
      - name: "Recover the coverage report from .coverage"
        uses: actions/download-artifact@v2
        with:
          name: Coverage-Report
      - name: "Run coverage"    
        run: coverage report
      - name: "Converting to xml"
        run: coverage xml
      - name: "Adding converted report"
        uses: actions/upload-artifact@v2
        with:
          name: Coverage-Report
          path: coverage.xml
          retention-days: 14
                    
  
